#!/usr/bin/env node
// scan-repos.mjs — keep the repo-map artifact's embedded data honest.
//
// The repo-map artifact (src/repo-map/artifact.html) bakes in a
// REPOS object + EDGES array describing the EarlBear ecosystem. The PROSE in it
// (each repo's purpose, each edge's reason) is human-authored and can't be
// regenerated by regex. But the STRUCTURE — which earlbear-* repos exist, their
// git remotes, and the build-time `file:` dependencies between them — is
// mechanically scannable. This script scans the sibling repos, parses the data
// currently embedded in the artifact, and DIFFS them, so drift is caught instead
// of silently rotting.
//
// It deliberately does NOT rewrite artifact.html. Structural drift becomes a
// checklist for a human (or Claude invoking this skill) to fold in by hand,
// preserving the curated purpose/reason prose. Think `git status`, not `git add`.
//
// Usage:
//   scan-repos.mjs [--root <dir>] [--artifact <path>] [--json]
//
//   --root <dir>      directory holding the earlbear-* siblings
//                     (default: two levels above the repo root, i.e. ~/Workspace/git)
//   --artifact <path> path to repo-map artifact.html (default: resolved from skill)
//   --json            emit the machine-readable diff as JSON instead of a report
//
// Exit: 0 no drift · 1 drift found (repos/remotes/file-dep edges differ) · 2 usage/IO.
//
// Pure helpers (parseEmbeddedData, detectFileDeps, fileDepEdges, diffMap) are
// exported for node:test.

import { readFileSync, readdirSync, existsSync, statSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve, join, basename } from 'node:path'
import { execFileSync } from 'node:child_process'

// ── pure core (unit-tested) ──────────────────────────────────────────────────

// Pull the REPOS object and EDGES array out of the artifact's <script> block.
// We don't eval the file (it references `window`, mermaid, the DOM). Instead we
// slice each literal by brace/bracket matching and JSON-ify the JS-object source.
export function parseEmbeddedData(html) {
  const repos = sliceLiteral(html, /var\s+REPOS\s*=\s*/, '{', '}')
  const edges = sliceLiteral(html, /var\s+EDGES\s*=\s*/, '[', ']')
  const ignore = sliceLiteral(html, /var\s+IGNORE_REPOS\s*=\s*/, '[', ']')
  return {
    repos: repos ? jsObjectToJson(repos) : {},
    edges: edges ? jsObjectToJson(edges) : [],
    ignore: ignore ? jsObjectToJson(ignore) : [],
  }
}

// Find `<assignRe>` then brace/bracket-match the literal that follows.
function sliceLiteral(text, assignRe, open, close) {
  const m = assignRe.exec(text)
  if (!m) return null
  const start = text.indexOf(open, m.index + m[0].length)
  if (start < 0) return null
  let depth = 0
  let inStr = false
  let strCh = ''
  for (let i = start; i < text.length; i++) {
    const c = text[i]
    if (inStr) {
      if (c === '\\') { i++; continue }
      if (c === strCh) inStr = false
      continue
    }
    if (c === '"' || c === "'") { inStr = true; strCh = c; continue }
    if (c === open) depth++
    else if (c === close) { depth--; if (depth === 0) return text.slice(start, i + 1) }
  }
  return null
}

// Convert a (trusted, our-own) JS object/array literal into JSON we can parse:
// quote bare keys, normalize single-quoted strings, strip trailing commas and
// line comments. Scoped to the simple literals we author in artifact.html.
export function jsObjectToJson(src) {
  let s = src
  // strip // line comments (not inside strings — our data has none mid-string)
  s = s.replace(/(^|[^:])\/\/[^\n]*/g, '$1')
  // single-quoted -> double-quoted strings
  s = s.replace(/'((?:[^'\\]|\\.)*)'/g, (_, inner) => '"' + inner.replace(/"/g, '\\"') + '"')
  // bare object keys -> quoted keys:  { foo: ...  or  , foo:
  s = s.replace(/([{,]\s*)([A-Za-z_$][\w$]*)\s*:/g, '$1"$2":')
  // trailing commas before } or ]
  s = s.replace(/,(\s*[}\]])/g, '$1')
  return JSON.parse(s)
}

// Detect build-time `file:` dependencies declared in a package.json's
// dependencies/devDependencies. Returns the raw file: target paths.
export function detectFileDeps(pkgJson) {
  const out = []
  for (const field of ['dependencies', 'devDependencies', 'peerDependencies']) {
    const deps = pkgJson && pkgJson[field]
    if (!deps) continue
    for (const [name, spec] of Object.entries(deps)) {
      if (typeof spec === 'string' && spec.startsWith('file:')) {
        out.push({ name, target: spec.slice('file:'.length) })
      }
    }
  }
  return out
}

// Given a repo slug and the file: targets found anywhere in it, resolve each
// target path to the sibling repo it points at and emit dep edges (from -> to).
// `knownSlugs` is the set of repo dir names we scanned, so we only emit edges
// between repos that are actually in the map.
export function fileDepEdges(slug, fileTargets, knownSlugs) {
  const edges = []
  for (const t of fileTargets) {
    // file: targets are relative; the last path segment that matches a known
    // repo slug is the target repo.
    const segs = t.target.split('/').filter(Boolean)
    let to = null
    for (let i = segs.length - 1; i >= 0; i--) {
      if (knownSlugs.has(segs[i])) { to = segs[i]; break }
    }
    if (to && to !== slug) edges.push({ from: slug, to })
  }
  // dedupe
  const seen = new Set()
  return edges.filter((e) => {
    const k = e.from + '->' + e.to
    if (seen.has(k)) return false
    seen.add(k)
    return true
  })
}

// Diff scanned structural facts against the embedded map.
// scanned: { repos: {slug: {remote, fileDepTargets}}, depEdges: [{from,to}] }
// embedded: { repos: {slug: {...}}, edges: [{from,to,kind,...}] }
export function diffMap(scanned, embedded) {
  const ignore = new Set(embedded.ignore || [])
  const scannedSlugs = Object.keys(scanned.repos)
  const embeddedSlugs = Object.keys(embedded.repos)
  const sSet = new Set(scannedSlugs)
  const eSet = new Set(embeddedSlugs)

  // intentionally-ignored sibling dirs (local aliases, non-repos) aren't "new".
  const newRepos = scannedSlugs.filter((s) => !eSet.has(s) && !ignore.has(s))
  const removedRepos = embeddedSlugs.filter((s) => !sSet.has(s))

  // remote changes (only for repos in both; ignore "(local only)" placeholders)
  const remoteChanges = []
  for (const slug of scannedSlugs) {
    if (!eSet.has(slug)) continue
    const scannedRemote = scanned.repos[slug].remote
    const embeddedRemote = embedded.repos[slug].remote
    if (scannedRemote && embeddedRemote &&
        embeddedRemote !== '(local only)' &&
        normRemote(scannedRemote) !== normRemote(embeddedRemote)) {
      remoteChanges.push({ slug, scanned: scannedRemote, embedded: embeddedRemote })
    }
  }

  // file: dependency edges present on disk but missing from the embedded EDGES,
  // and embedded "dep" edges no longer backed by a file: dep on disk.
  const embeddedDepKeys = new Set(
    embedded.edges.filter((e) => e.kind === 'dep').map((e) => e.from + '->' + e.to),
  )
  const scannedDepKeys = new Set(scanned.depEdges.map((e) => e.from + '->' + e.to))
  const newDepEdges = scanned.depEdges.filter(
    (e) => !embeddedDepKeys.has(e.from + '->' + e.to),
  )
  const staleDepEdges = embedded.edges
    .filter((e) => e.kind === 'dep' && !scannedDepKeys.has(e.from + '->' + e.to))
    .map((e) => ({ from: e.from, to: e.to }))

  const hasDrift =
    newRepos.length > 0 || removedRepos.length > 0 || remoteChanges.length > 0 ||
    newDepEdges.length > 0 || staleDepEdges.length > 0

  return { newRepos, removedRepos, remoteChanges, newDepEdges, staleDepEdges, hasDrift }
}

// Normalize a remote to "org/name" for comparison (handles full git URLs and
// the "org/name" shorthand the artifact stores).
export function normRemote(remote) {
  if (!remote) return ''
  let r = remote.trim()
  r = r.replace(/^git@[^:]+:/, '').replace(/^https?:\/\/[^/]+\//, '')
  r = r.replace(/\.git$/, '')
  return r.toLowerCase()
}

// ── scanning (IO) ────────────────────────────────────────────────────────────

function gitRemote(dir) {
  try {
    const out = execFileSync('git', ['-C', dir, 'remote', 'get-url', 'origin'], {
      encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'],
    }).trim()
    return out || '(local only)'
  } catch {
    return '(local only)'
  }
}

// Find all package.json files in a repo (shallow-ish: skip node_modules, dist,
// .git) and collect their file: dep targets.
function collectFileDeps(dir) {
  const targets = []
  const SKIP = new Set(['node_modules', '.git', 'dist', 'build', '.next', '.cache'])
  const walk = (d, depth) => {
    if (depth > 4) return
    let entries
    try { entries = readdirSync(d, { withFileTypes: true }) } catch { return }
    for (const ent of entries) {
      if (ent.isDirectory()) {
        if (SKIP.has(ent.name)) continue
        walk(join(d, ent.name), depth + 1)
      } else if (ent.name === 'package.json') {
        try {
          const pkg = JSON.parse(readFileSync(join(d, ent.name), 'utf8'))
          targets.push(...detectFileDeps(pkg))
        } catch { /* ignore unparseable package.json */ }
      }
    }
  }
  walk(dir, 0)
  return targets
}

export function scanRepos(rootDir) {
  let names
  try {
    names = readdirSync(rootDir, { withFileTypes: true })
      .filter((e) => e.isDirectory() && /earlbear/i.test(e.name))
      .map((e) => e.name)
  } catch (e) {
    throw new Error(`cannot read root dir ${rootDir}: ${e.message}`)
  }
  const knownSlugs = new Set(names)
  const repos = {}
  let depEdges = []
  for (const name of names) {
    const dir = join(rootDir, name)
    const fileTargets = collectFileDeps(dir)
    repos[name] = { remote: gitRemote(dir), fileDepTargets: fileTargets }
    depEdges = depEdges.concat(fileDepEdges(name, fileTargets, knownSlugs))
  }
  return { repos, depEdges }
}

// ── report ───────────────────────────────────────────────────────────────────

function report(diff) {
  const L = []
  if (!diff.hasDrift) {
    L.push('✓ repo-map is in sync with the scanned ecosystem (no structural drift).')
    return L.join('\n')
  }
  L.push('Repo-map structural drift detected — fold these into')
  L.push('src/repo-map/artifact.html by hand (purpose/reason prose is curated):')
  L.push('')
  if (diff.newRepos.length) {
    L.push('  NEW repos on disk, missing from the map (add to REPOS + author a purpose):')
    diff.newRepos.forEach((s) => L.push(`    + ${s}`))
  }
  if (diff.removedRepos.length) {
    L.push('  REMOVED — in the map but not on disk (delete from REPOS + its EDGES):')
    diff.removedRepos.forEach((s) => L.push(`    - ${s}`))
  }
  if (diff.remoteChanges.length) {
    L.push('  REMOTE changed (update the repo\'s `remote` field):')
    diff.remoteChanges.forEach((c) => L.push(`    ~ ${c.slug}: map="${c.embedded}" disk="${c.scanned}"`))
  }
  if (diff.newDepEdges.length) {
    L.push('  NEW file: dependency edges on disk, missing from EDGES (add kind:"dep" + a reason):')
    diff.newDepEdges.forEach((e) => L.push(`    + ${e.from} --> ${e.to}`))
  }
  if (diff.staleDepEdges.length) {
    L.push('  STALE dep edges in the map, no longer backed by a file: dep on disk (verify/remove):')
    diff.staleDepEdges.forEach((e) => L.push(`    ? ${e.from} --> ${e.to}`))
  }
  L.push('')
  L.push('Note: only `dep` (file:) edges are auto-verified. `flow` edges (sync/publish/')
  L.push('shared-infra) are prose-derived and never flagged — review them manually.')
  return L.join('\n')
}

// ── arg parsing + main (thin CLI shell) ──────────────────────────────────────

function parseArgs(argv) {
  const out = {}
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i]
    if (a.startsWith('--')) {
      const key = a.slice(2)
      if (key === 'json') { out.json = true; continue }
      out[key] = argv[++i]
    }
  }
  return out
}

function main(argv) {
  const a = parseArgs(argv)
  const here = dirname(fileURLToPath(import.meta.url))
  // skill at .claude/skills/manage-repo-map/scripts/ → repo root is 4 up.
  const repoRoot = resolve(here, '../../../../')
  // In earlbear-blog the artifact is vendored at src/repo-map/artifact.html and
  // served by src/pages/repo-map.astro (internal-only). It moved here from
  // earlbear-sites (claude-artifacts/repo-map/), where the sites copy no longer
  // exists — this blog copy is now canonical.
  const artifactPath = a.artifact
    ? resolve(a.artifact)
    : join(repoRoot, 'src/repo-map/artifact.html')
  // default scan root: the dir holding the earlbear-* siblings. The blog lives at
  // ~/Workspace/git-earlbear/earlbear-blog, so the parent (dirname of repoRoot)
  // holds the sibling earlbear-* repos — same relationship as in earlbear-sites.
  const rootDir = a.root ? resolve(a.root) : dirname(repoRoot)

  let html
  try {
    html = readFileSync(artifactPath, 'utf8')
  } catch (e) {
    process.stderr.write(`cannot read artifact at ${artifactPath}: ${e.message}\n`)
    return 2
  }

  let embedded
  try {
    embedded = parseEmbeddedData(html)
    if (!Object.keys(embedded.repos).length) throw new Error('no REPOS parsed from artifact')
  } catch (e) {
    process.stderr.write(`cannot parse embedded data: ${e.message}\n`)
    return 2
  }

  if (!existsSync(rootDir) || !statSync(rootDir).isDirectory()) {
    process.stderr.write(`scan root is not a directory: ${rootDir}\n`)
    return 2
  }

  let scanned
  try {
    scanned = scanRepos(rootDir)
  } catch (e) {
    process.stderr.write(`scan failed: ${e.message}\n`)
    return 2
  }

  const diff = diffMap(scanned, embedded)

  if (a.json) {
    process.stdout.write(JSON.stringify(diff, null, 2) + '\n')
  } else {
    process.stdout.write(report(diff) + '\n')
  }
  return diff.hasDrift ? 1 : 0
}

// Only run main when invoked directly (not when imported by the test).
if (import.meta.url === `file://${process.argv[1]}`) {
  process.exit(main(process.argv.slice(2)))
}
